### PR TITLE
migration to webauthn

### PR DESCRIPTION
**Pull request by brianjp93**
- remove dependency on u2flib server, use webauthn
- edit relevant tests

### CODE REVIEW

**Comment by justinmayer** [comment]
Hey Brian. While only tangentially related to your pull request, I thought I would mention that I created a new MFA-for-Django project called [Kagi](https://github.com/justinmayer/kagi) that you might want to check out. From its inception, it has utilized the [`webauthn`](https://pypi.org/project/webauthn/) library and has full 100% test coverage. ✨

**Comment by nolsto** [comment]
Its "inception" consisted of copying (not forking) the code from this very repo without a mention to @gavinwahl.

https://github.com/justinmayer/kagi/commit/94e1f582bc4e61d62dccc34e5c1df8c84dffe14d

You didn't violate [the license](https://github.com/justinmayer/kagi/blob/9e934ae0c27cecdbe5c01c9c486199e890513590/LICENSE#L3) in doing so, but you weren't acting in the spirit of open-source software development.

Maybe acknowledge this fact before trying to drum up support for your work.

**Comment by gavinwahl** [comment]
Great work @brianjp93, thank you

**Comment by justinmayer** [comment]
Hey Nolan. Thank you for pointing this out. You are quite right that I forgot to provide adequate attribution to @gavinwahl, an accidental oversight that I sincerely regret. I have corrected that by adding [appropriate credit](https://github.com/justinmayer/kagi/commit/cbc3da7e5e048f0f62da597252f99deff1438c93) to the README, to which Gavin is indeed rightfully due. My apologies to Gavin for the error.

My intention in posting here was not self-promotion but merely to provide information that might be useful. As a side note, if you have a look at the [relevant diff](https://github.com/justinmayer/kagi/compare/94e1f582bc4e61d62dccc34e5c1df8c84dffe14d...main#files_bucket), you will see that we used the django-u2f code as initial scaffolding, with few lines from the initial import used in the current project.

Nonetheless, while the missing attribution was entirely accidental, you are correct that the end result was not in the spirit of open-source software development, and I appreciate you mentioning that here so I could correct that mistake. Thanks again.

**Pull request merged**
